name: Docker Image to Source (Compressed)

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'نام کامل ایمیج (مثلاً ghcr.io/user/repo:tag)'
        required: true

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull, Save and Compress
        run: |
          # 1. دانلود ایمیج
          docker pull ${{ github.event.inputs.image_name }}
          
          # 2. تمیز کردن نام برای ساخت پوشه
          SAFE_NAME=$(echo "${{ github.event.inputs.image_name }}" | sed 's/[\/:]/_/g')
          
          # 3. ذخیره و فشرده‌سازی با حداکثر توان (فایل نهایی خیلی کوچکتر می‌شود)
          docker save ${{ github.event.inputs.image_name }} | gzip > image.tar.gz
          
          # 4. ساخت پوشه مقصد
          mkdir -p "downloads/$SAFE_NAME"
          
          # 5. تکه تکه کردن فایل فشرده به پارت‌های 50 مگابایتی
          split -b 50M -d image.tar.gz "downloads/$SAFE_NAME/part_"
          
          # 6. حذف فایل اصلی فشرده شده (حیاتی برای جلوگیری از ارور حجم گیت‌هاب)
          rm image.tar.gz
          
          echo "DIR_NAME=downloads/$SAFE_NAME" >> $GITHUB_ENV

      - name: Commit and Push to Source
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # فقط پوشه دانلودها را اضافه کن
          git add downloads/
          
          # بررسی برای جلوگیری از ارور در صورت نبود تغییر
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add compressed Docker image: ${{ github.event.inputs.image_name }}"
            git push
          fi
          #cat part_* > sql19.tar.gz  
